[package]
name = "bohemia-compression"
version = "0.0.1-dev"
edition = "2021"
rust-version = "1.56"

[features]
default = []
checked_write = []

[dependencies]
derive_more = "0.99.17"
itertools = "0.10.3"
